app/Http/routes.php
<?php
use App\Option;
use App\Site;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('sites/testing', 'SiteController@testing');

Route::get('sites/get_db_info', 'SiteController@get_db_info');

Route::get('sites/get_cms_info', 'SiteController@get_cms_info');

Route::get('sites/export','SiteController@export');

Route::get('sites/snapshots','SiteController@snapshots');

Route::get('sites/backups','SiteController@backups');

Route::post('snapshot_creation','SiteController@snapshot_creation');

Route::post('restore_backup','SiteController@restore_backup');

Route::post('delete_backup','SiteController@delete_backup');

Route::get('sites/addkeys','SiteController@addkeys');

Route::get('sites/add_alias','SiteController@add_alias');

Route::get('sites/get_sites','SiteController@get_sites');

Route::get('sites/trash','SiteController@trash');

Route::get('sites/suspend','SiteController@suspend');

Route::get('sites/site_continue','SiteController@site_continue');

Route::get('sites/restore','SiteController@restore');

Route::get('sites/search','SiteController@search');

Route::get('sites/wordpress_plus_laravel','SiteController@wordpress_plus_laravel');

Route::get('sites/laravel','SiteController@laravel');

Route::post('force_delete', 'SiteController@force_delete');

Route::get('update_license','OregisterController@update_license');

Route::get("reload_server",'SiteController@reload_server');

Route::get('register_your_license','OregisterController@register_your_license');

Route::resource("sites","SiteController");

Route::resource("options","OptionController");

Route::resource("adomains","AdomainController");


// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

//API ACTIONS ROUTES
Route::get('/list_backups', 'APIController@list_backups');
Route::get('/delete_backup', 'APIController@delete_backup');
Route::get('/list_sites', 'APIController@list_sites');
Route::get('/list_trash', 'APIController@list_trash');

//Admin Routes
Route::get('/list_users', 'AdminController@list_users');
Route::get('/edit_user', 'AdminController@edit_user');
Route::post('/delete_user', 'AdminController@delete_user');

Route::get('/pete_plugins','BaseController@pete_plugins');
Route::post('/pete_plugins_install','BaseController@pete_plugins_install');
Route::post('/pete_plugins_uninstall','BaseController@pete_plugins_uninstall');
Route::post('/pete_plugins_update','BaseController@pete_plugins_update');

Route::get('/get_domains', function () {
	
	$sites = Site::orderBy('id', 'desc')->get();
    return response()->json($sites);
});


Route::get('/', array('as' => 'sites.index', 'uses' => 'SiteController@index'));
Route::get('/home', array('as' => 'sites.index', 'uses' => 'SiteController@index'));

app/Option.php
<?php

namespace App;
use Log;
use Illuminate\Database\Eloquent\Model;

class Option extends Model
{
    //
	
	public static function delete_meta_value($key){
		$object = Option::where('option_name',$key)->first();
		Log::info('Entro en delete_meta_value');
		if($object){
		   $object->delete();
		   Log::info('Entro en borrado');
		}
	}
	
	public static function get_meta_value($key){
		$object = Option::where('option_name',$key)->first();
		if(isset($object)){
			return $object->option_value;
		}else{
			return "";
		}		
	}
}

app/Http/Controllers/OptionController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Option;
use Illuminate\Http\Request;

class OptionController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	
	public function __construct()
	    {
	        $this->middleware('auth');
			//$this->middleware('auth.check_logic');
	    }
	
	public function index()
	{
		$viewsw = "options";
		$options = Option::where("visible",true)->orderBy('id', 'desc')->paginate(25);

		return view('options.index', compact('options','viewsw'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$viewsw = "options";
		return view('options.create',compact('viewsw'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		
		$option = new Option();

		$option->option_name = $request->input("option_name");
        $option->option_value = $request->input("option_value");
		$option->visible = true;
		$option->save();

		return redirect()->route('options.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$viewsw = "options";
		$option = Option::findOrFail($id);

		return view('options.show', compact('option','viewsw'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$viewsw = "options";
		$option = Option::findOrFail($id);

		return view('options.edit', compact('option','viewsw'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$option = Option::findOrFail($id);

		$option->option_name = $request->input("option_name");
        $option->option_value = $request->input("option_value");

		$option->save();

		return redirect()->route('options.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$option = Option::findOrFail($id);
		$option->delete();

		return redirect()->route('options.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/options/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h3>Create new Option</h3>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('options.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group">
                       <label for="option_name-field">Option_name</label>
                    <input type="text" id="option_name-field" name="option_name" class="form-control" value="{{ old("option_name") }}"/>
                      
                    </div>
                    <div class="form-group">
                       <label for="option_value-field">Option_value</label>
                    <input type="text" id="option_value-field" name="option_value" class="form-control" value="{{ old("option_value") }}"/>
                    </div>
               
                    <button type="submit" class="btnpete">Create option</button>
                
            </form>

        </div>
    </div>
@endsection

resources/views/options/edit.blade.php
@extends('layout')

@section('header')
   
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('options.update', $option->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('option_name')) has-error @endif">
                       <label for="option_name-field">Option_name</label>
                    <input type="text" id="option_name-field" name="option_name" class="form-control" value="{{ $option->option_name }}"/>
                       @if($errors->has("option_name"))
                        <span class="help-block">{{ $errors->first("option_name") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('option_value')) has-error @endif">
                       <label for="option_value-field">Option_value</label>
                    <input type="text" id="option_value-field" name="option_value" class="form-control" value="{{ $option->option_value }}"/>
                       @if($errors->has("option_value"))
                        <span class="help-block">{{ $errors->first("option_value") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('options.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/options/index.blade.php
@extends('layout')

@section('header')
  
     

  
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
			
	        <h1>
			
	            <a class="btnpete pull-right" href="{{ route('options.create') }}"><i class="glyphicon glyphicon-plus"></i> Create Option</a>
	        </h1>
			
			<div class="content table-responsive table-full-width">
			                               
            @if($options->count())
                 <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>OPTION_NAME</th>
                        <th>OPTION_VALUE</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($options as $option)
                            <tr>
                                <td>{{$option->id}}</td>
                                <td>{{$option->option_name}}</td>
                    <td>{{$option->option_value}}</td>
                                <td class="text-right">
                                    
                                    <a class="btn btn-xs btn-warning" href="{{ route('options.edit', $option->id) }}">Edit</a>
                                    <form action="{{ route('options.destroy', $option->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $options->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif
			 </div>
        </div>
    </div>

@endsection

resources/views/options/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Options / Show #{{$option->id}}</h1>
        <form action="{{ route('options.destroy', $option->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('options.edit', $option->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="option_name">OPTION_NAME</label>
                     <p class="form-control-static">{{$option->option_name}}</p>
                </div>
                    <div class="form-group">
                     <label for="option_value">OPTION_VALUE</label>
                     <p class="form-control-static">{{$option->option_value}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('options.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection