app/Http/routes.php
<?php
use App\Option;
use App\Site;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('sites/testing', 'SiteController@testing');

Route::get('sites/get_db_info', 'SiteController@get_db_info');

Route::get('sites/get_cms_info', 'SiteController@get_cms_info');

Route::get('sites/export','SiteController@export');

Route::get('sites/snapshots','SiteController@snapshots');

Route::get('sites/backups','SiteController@backups');

Route::post('snapshot_creation','SiteController@snapshot_creation');

Route::post('restore_backup','SiteController@restore_backup');

Route::post('delete_backup','SiteController@delete_backup');

Route::get('sites/addkeys','SiteController@addkeys');

Route::get('sites/add_alias','SiteController@add_alias');

Route::get('sites/get_sites','SiteController@get_sites');

Route::get('sites/trash','SiteController@trash');

Route::get('sites/suspend','SiteController@suspend');

Route::get('sites/site_continue','SiteController@site_continue');

Route::get('sites/restore','SiteController@restore');

Route::get('sites/search','SiteController@search');

Route::get('sites/wordpress_plus_laravel','SiteController@wordpress_plus_laravel');

Route::get('sites/laravel','SiteController@laravel');

Route::post('force_delete', 'SiteController@force_delete');

Route::get('update_license','OregisterController@update_license');

Route::get("reload_server",'SiteController@reload_server');

Route::get('register_your_license','OregisterController@register_your_license');

Route::resource("sites","SiteController");

Route::resource("options","OptionController");

Route::resource("adomains","AdomainController");


// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

//API ACTIONS ROUTES
Route::get('/list_backups', 'APIController@list_backups');
Route::get('/delete_backup', 'APIController@delete_backup');
Route::get('/list_sites', 'APIController@list_sites');
Route::get('/list_trash', 'APIController@list_trash');

//Admin Routes
Route::get('/list_users', 'AdminController@list_users');
Route::get('/edit_user', 'AdminController@edit_user');
Route::post('/delete_user', 'AdminController@delete_user');

Route::get('/pete_plugins','BaseController@pete_plugins');
Route::post('/pete_plugins_install','BaseController@pete_plugins_install');
Route::post('/pete_plugins_uninstall','BaseController@pete_plugins_uninstall');
Route::post('/pete_plugins_update','BaseController@pete_plugins_update');

Route::get('/get_domains', function () {
	
	$sites = Site::orderBy('id', 'desc')->get();
    return response()->json($sites);
});


Route::get('/', array('as' => 'sites.index', 'uses' => 'SiteController@index'));
Route::get('/home', array('as' => 'sites.index', 'uses' => 'SiteController@index'));

app/Http/Controllers/SiteController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Log;
use App\Site;
use App\Adomain;
use App\Secure;
use App\User;
use App\Backup;
use Input;
use Response;
use App\App;
use Validator;
use App\Option;
use DB;
use App\Pete;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Illuminate\Support\Facades\Redirect;
use App\PeteOption;
use Illuminate\Routing\Route;
use Illuminate\Support\MessageBag;

class SiteController extends Controller {

	
	public function __construct(Route $route){
	        
	       	$this->middleware('auth');
			//$this->middleware('auth.check_logic');
	 }
	 
	public function snapshot_creation(){
		
		Log::info("snapshot_creation:");
		
		$label = Input::get('snapshot_label_form');
		$site_id = Input::get('site_id_form');
		
		//ERROR CASES FOR BACKUP MODEL
		//1. LABEL FORMAT 
		//2. SITE_ID AND LABEL UNIQUE
		
		if(!preg_match('/^[a-zA-Z0-9-_]+$/',$label)){
			return redirect('/sites')->withErrors(['Label' => 'Label format error. Please use only letters, numbers, -, or _ for characters']);
		}
		
		$check_backup = Backup::where("label",$label)->where("site_id",$site_id)->first();
		if(isset($check_backup)){
			return redirect('/sites')->withErrors(['Label' => 'This label is already used.']);
		}
		
		$site = Site::findOrFail(Input::get('site_id_form'));
		$site->snapshot_creation(Input::get('snapshot_label_form'));
		$site->save();
		
		return Redirect::to('/sites/snapshots');
	}
	
	public function restore_backup(){
		
		//3 CASES
		//1 RESTORE TO NEW DOMAIN RANDOM DOMAIN
		//2 RESTORE TO NEW DOMAIN WITH DOMAIN PARAM
		//3 RESTORE TO SITE CURRENT DOMAIN
		
		Log::info("backup_id_form: ".Input::get('backup_id_form'));
		Log::info("domain_form: ".Input::get('domain_form'));
		Log::info("backup_action_form: ".Input::get('backup_action_form'));
		
		$backup_id = Input::get('backup_id_form');
		$domain = Input::get('domain_form');
		$backup_action = Input::get('backup_action_form');
		
		$backup = Backup::findOrFail($backup_id);
		$pete_options = new PeteOption();
		$app_root = $pete_options->get_meta_value('app_root');
		$domain_template = $pete_options->get_meta_value('domain_template');
		$backup_file = "$app_root/Pete/backups/$backup->site_id/$backup->name-$backup->schedulling.tar.gz";
		
		//CASE 1
		if(($backup_action == "restore_to_new_domain") & ($domain=="")){
			
			$new_site = new Site();
			$new_site->theme = $backup->theme;
			$new_site->action_name = "Backup Restore";
			$new_site->name = $backup->generate_uniq_name();
			$new_site->url = $new_site->name.".".$domain_template;
			
		}else if(($backup_action == "restore_to_new_domain") & ($domain!="")){
			
			$check_site = Site::where("url",$domain)->first();
			if(isset($check_site)){
				return redirect('/sites')->withErrors(['URL' => 'This URL is already used.']);
			}
			
			$uniqid = uniqid();
			$uniqid = "restore_".$uniqid;
			$new_site = new Site();
			$new_site->theme = $backup->theme;
			$new_site->action_name = "Backup Restore";
			$new_site->name = $uniqid.$backup->name;
			$new_site->url = $domain;
			
		}else if($backup_action == "restore_to_current_domain"){
			
			$uniqid = uniqid();
			$uniqid = "restore_".$uniqid;
			$new_site = new Site();
			$new_site->theme = $backup->theme;
			$new_site->action_name = "Backup Restore";
			$new_site->name = $uniqid.$backup->name;
			$new_site->url = $backup->url;
			
			$site_to_replace = Site::where("url",$backup->url)->first();
			if(isset($site_to_replace)){
				$site_to_replace->delete_wordpress();
				$site_to_replace->delete();
			}
		}
		
		$new_site->import_wordpress($backup_file);
		return Redirect::to('/sites?success=true');
	}
	
	public function snapshots(){

		//$backups = Backup::orderBy('backups.id', 'desc')->where("manual",true)->get();
		$user = Auth::user();
		
		$backups = Backup::orderBy('backups.created_at', 'asc')
			    ->select(DB::raw('backups.id, backups.schedulling, backups.file_name,sites.name, sites.url'))
				->join('sites', 'sites.id', '=', 'backups.site_id')
				->where("sites.user_id",$user->id)->where("manual",true)->get();
		
		$viewsw = "sites";
		return view('sites.backups', compact('backups','viewsw'));
		
	}
	
	public function backups(){
		
		$user = Auth::user();
		
		$backups = Backup::orderBy('backups.created_at', 'asc')
			    ->select(DB::raw('backups.id, backups.schedulling, backups.file_name,sites.name, sites.url'))
				->join('sites', 'sites.id', '=', 'backups.site_id')
				->where("sites.user_id",$user->id)->where("manual",false)->get();
		
		$viewsw = "sites";
		return view('sites.backups', compact('backups','viewsw'));
		
	}
	
	public function delete_backup(){
		
		$backup = Backup::findOrFail(Input::get('backup_id'));
		$view = Input::get('view');
		$backup->delete();
		return Redirect::to("/sites/$view");
		
	}
	
	
	
	public function register_your_license(){
		
		$viewsw = "sites";
		$validation_url = Option::get_meta_value('validation_url');
		return view('oregisters.register_your_license', compact('validation_url','viewsw'));
		
	}
	
	
	public function export(){
		
		$viewsw = "sites";
		$site = Site::findOrFail(Input::get('id'));
		$site->export_wordpress();
		$exporturl = $site->file_to_download;
		$sites = Site::orderBy('id', 'desc')->paginate(10);
		return view('sites.index', compact('sites','exporturl','viewsw'));
	  
	}
	
	public function reload_server(){
		
		Site::reload_server();
		return response()->json(["OK" => "OK"]);  
	}
	
	public function trash(){
		
		$user = Auth::user();
		$viewsw = "trash";
		$sites = $user->my_trash_sites()->paginate(10);
		return view('sites.trash', compact('sites','viewsw'));
		
	}
	
	public function suspend(){
		
		$site = Site::findOrFail(Input::get('id'));
		$site->suspend = true;
		$site->suspend_wordpress();
		$site->save();
		return Redirect::to('/?success=true&site_id='.$site->id);
	  
	}
	
	public function site_continue(){
		
		$site = Site::findOrFail(Input::get('id'));
		$site->suspend = false;
		$site->continue_wordpress();
		$site->save();
		return Redirect::to('/?success=true&site_id='.$site->id);
	  
	}
	
	public function get_sites(){
		
		$app_name = Input::get('app_name');
		if($app_name == "Wordpress"){
		  $result = Site::where('app_name', "Wordpress")->orderBy('id', 'desc')->get();
		}else if($app_name == "Wordpress+laravel"){
		  $result = Site::where('app_name', "Wordpress")->orderBy('id', 'desc')->get();
		  for ($i = 0; $i < count($result); $i++) {
			if(substr_count($result[0]->domain, '.') > 2) {
				unset($array[$i]);
			}
			  
		  }
		}
	    return response()->json($result);
	  
	}
	
	
	public function restore(){
		$site = Site::withTrashed()->findOrFail(Input::get('id'));
		$site->restore();
		$site->restore_wordpress();
		return Redirect::to('/?success=true&site_id='.$site->id);
	}
	
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$user = Auth::user();
		$viewsw = "/sites";
		
		if($user->admin){
			$sites = Site::orderBy('id', 'desc')->where("app_name","WordPress")->paginate(50);
		}else{
			$sites = $user->my_sites()->where("app_name","WordPress")->paginate(10);
		}
		
		$success = Input::get('success');
		$site_id = Input::get('site_id');
		return view('sites.index', compact('sites','success','site_id','viewsw'));
	}
	
	public function search()
	{
		$viewsw = "sites";
	    $sites = Site::orderBy('id', 'desc')->where('url', 'like', '%' . Input::get('data') . '%')->paginate(50);
		$data = Input::get('data');
		return view('sites.index', compact('sites','current_user','first_time','viewsw','data'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{   
		$viewsw = "/sites";
		return view('sites.create',compact('sites','viewsw'));
	}
	
	public function wordpress_plus_laravel(){
		
		$num = substr(PHP_VERSION, 0, 3);
		$float_version = (float)$num;
		
		if($float_version < 7.1){
        	return redirect('sites/create')->withErrors("The PHP version must be >= 7.1 to activate WordPress Plus Laravel functionality.");
		}
		
		$viewsw = "wordpress+laravel";
		return view('sites.wordpress_plus_laravel',compact('viewsw'));
	}
	
	public function laravel(){
		
		$num = substr(PHP_VERSION, 0, 3);
		$float_version = (float)$num;
		
		if($float_version < 7.1){
        	return redirect('sites/create')->withErrors("The PHP version must be >= 7.1 to activate WordPress Plus Laravel functionality.");
		}
		
		$viewsw = "laravel";
		return view('sites.laravel',compact('viewsw'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$pete_options = new PeteOption();
		$user = Auth::user();
		$fields_to_validator = $request->all();
		
		$site = new Site();
		$site->output = "";
		$site->user_id = $user->id;
		$site->app_name = $request->input("app_name");
		$site->action_name = $request->input("action_name");
		$site->to_clone_project_id = $request->input("to_clone_project_id");
		$site->name = $request->input("name");
		$site->to_import_project = $request->input("to_import_project");
		$site->user_id = $user->id;
		$site->url = $request->input("url");
		$site->big_file_route = $request->input("big_file_route");
		$site->laravel_version = $request->input("selected_version");	
		
		if(($user->shared) & ($user->has_one_site())){
			return Redirect::back()->withErrors(['Please upgrade your plan.']);
		}
		
		$app_root = $pete_options->get_meta_value('app_root');
		if($pete_options->get_meta_value('domain_template')){
	
			$site->url = $site->url . "." . $pete_options->get_meta_value('domain_template');
		}
		
		$validator = Validator::make($fields_to_validator, [
			'name' =>  array('required', 'regex:/^[a-zA-Z0-9-_]+$/','unique:sites'),
			'url' => 'required|unique:sites',
		]);
		
     	if ($validator->fails()) {
			

resources/views/sites/_table_header.blade.php
	<div class="row">
				
					<div class="col-md-12">
						
						<a class="table_tab" href="/sites">Sites</a>
						
	                    <a class="table_tab" href="/sites/trash">Trash</a>
						
						@if($pete_options->get_meta_value('backups') == "on")
						
						<a class="table_tab" href="/sites/backups">Backups</a>
						
						@endif
						
						 @if($pete_options->get_meta_value('snapshots') == "on")
							<a class="table_tab" href="/sites/snapshots">Snapshots</a>
						@endif
					
					</div>
				
	</div>

resources/views/sites/backups.blade.php
@extends('layout')

@section('header')


		<div class="row">
	            
	        <div class="col-md-6">
    
        		<h1>
            		<img alt="w00t!" src="/pete.png" style="height: 204px">
			
					<p style="font-size: 13px; ">WordPress efficiency starts here.</p>
			
        		</h1>
		
			</div>
		
		 <div class="col-md-6">
			 <h1>
				 <a class="btnpete pull-right" href="{{ route('sites.create') }}"><i class="glyphicon glyphicon-plus"></i> Create New WordPress</a>
			 </h1>
		</div>
		
		</div>


@endsection

@section('content')


	@include('sites/_table_header')
	
    <div class="row">
        <div class="col-md-12">
			<div class="content table-responsive">
            @if($backups->count())
                <table style="padding-left: 10px; padding-right: 10px;" class="table table-hover table-striped">
                    <thead>
                        <tr>
                        <th>Project Name</th>
                        <th>Url</th>
                        <th>Label</th>
						<th>Filename</th>
                         <th class="text-right">Options</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($backups as $backup)
                            <tr>
                     		   <td>{{$backup->name}}</td>           
                    		   <td><a href="http://{{$backup->url}}" target ='_blank'>{{$backup->url}}</a></td>  
							   <td>{{$backup->schedulling}}</td>
							   <td>{{$backup->file_name}}</td>
							   
                                <td class="text-right">
									
									<a class="option_button restore_backup" backup_url="{{$backup->url}}" backup_id="{{$backup->id}}" href="#">Restore</a>
									
                                    <form action="/delete_backup" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
										
                                      <input type="hidden" name="_method" value="POST">
									  <input type="hidden" name="view" value="snapshots">
                                      <input type="hidden" name="_token" value="{{ csrf_token() }}">
										
										<input type="hidden" name="backup_id" value="{{$backup->id}}">
										
                                        <button type="submit" class="option_button" style="background-color: #f1592a; width: 100%">Delete</button>
                                    </form>
                                   
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            
            @else
               <table style="padding-left: 10px; padding-right: 10px;" class="table table-hover table-striped">
                    <thead>
                        <tr>
	                        <tr>
	                        <th>Id</th>
	                        <th>Project Name</th>
	                        <th>Url</th>
	                        <th>Label</th>
	                         <th class="text-right">Options</th>
	                        </tr>
                        </tr>
                    </thead>

                    <tbody>
					</tbody>
					
				</table>
            @endif
			</div>
        </div>
    </div>
	
	
	
	<div class="modal fade">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	        <h4 class="modal-title">Modal title</h4>
	      </div>
	      <div class="modal-body">
			<form id="site_form" action="/restore_backup" style="display:none" method="POST">
				<input type="hidden" name="_method" value="POST">
				<input type="hidden" name="_token" value="{{ csrf_token() }}">         
				
				<input type="hidden" id="backup_id_form" name="backup_id_form" value="">
				<input type="hidden" id="domain_form" name="domain_form" value="">
				<input type="hidden" id="backup_action_form" name="backup_action_form" value="">
				
			    <input type="submit" />
			</form>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <button type="button" class="btn btn-primary">Save changes</button>
	      </div>
	    </div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	
	
	
	<script type="text/javascript">
	
	
	   
	
    	$(document).ready(function(){
			
  			@if(isset($exporturl))
				console.log("download url: {{$exporturl}}");
  		  		window.location.assign("/{{$exporturl}}");
  		
  		  @endif
				
			
			$(".restore_backup").click(function() {
				
				backup_id = $(this).attr("backup_id");
				backup_url = $(this).attr("backup_url");
				
				html ='';
				html +='<select name="backup_action" id="backup_action">';
				html +='<option value="restore_to_new_domain">Restore to new domain</option>';
				html +='<option value="restore_to_current_domain">Restore to current domain: '+backup_url+'</option>';
				html +='</select> ';
				html +='<input id="domain" name="domain" value="">';
				
			    BootstrapDialog.show({
			          title: 'Restore Site',
			          message: html,
			          buttons: [{
			              label: '<a class ="btnpete">Restore Site</a>',
			              action: function(dialog) {
			                  // submit the form
							  //snapshot_label = $("#snapshot_label").val();
							  
							  $("#backup_id_form").val(backup_id);
							  $("#domain_form").val($("#domain").val());
							  $("#backup_action_form").val($("#backup_action").val());
							  
							//  $("#snapshot_label_form").val(snapshot_label);
							$('#site_form').submit();
							
							dialog.close();
							activate_webistebar_loader();
							
			              }
			          }]
			      });
				
			});
			
        	//demo.initChartist();
			/*
        	$.notify({
            	icon: 'pe-7s-arc',
            	message: "Welcome to the future of OZONE. Welcome to <b>Massive Server</b>"

            },{
                type: 'info',
                timer: 4000
            });
			*/
			
			
		   @if(isset($success))
			
			@if($success == "true")
			
		    var delayInMilliseconds = 3000; //1 second

		    setTimeout(function() {
		      //your code to be executed after 1 second
		   	 $("#loadMe").modal("hide");
		    }, delayInMilliseconds);

		     $.ajax({
		           url: "/reload_server",
		           type: "get",
		           datatype: 'json',
				   data: {site_id : "{{$site_id}}}"},
		           success: function(data){
		            // alert("success");	
	
		           }
		
		     });

		    @endif
			 
		  @endif	
		   

    	});
		
		
	</script>
	

@endsection

resources/views/sites/index.blade.php
@extends('layout')

@section('header')

	
	@if (count($errors) > 0)
	    <div class="alert alert-danger">
	        <strong>Whoops! Something went wrong!</strong>

	        <br><br>
	        <ul>
	            @foreach ($errors->all() as $error)
	                <li>{{ $error }}</li>
	            @endforeach
	        </ul>
	    </div>
	@endif
	
	

		<div class="row">
	            
	        <div class="col-md-4">
    
        	
            		<img alt="w00t!" src="/pete.png" style="height: 204px">
			
					<p style="font-size: 13px; ">WordPress efficiency starts here.</p>
		
			</div>
		
		 <div class="col-md-8">
			 <br /><br />
				 <a style="margin-top: 120px" class="btnpete" href="/sites/create"><i class="glyphicon glyphicon-plus"></i> Create WordPress</a>
			<br /><br /><br />
			 
		</div>
		
		</div>
		

@endsection

@section('content')


	@include('sites/_table_header')
	
    <div class="row">
        <div class="col-md-12">
			<div class="content table-responsive">
            @if($sites->count())
                <table style="padding-left: 10px; padding-right: 10px;" class="table table-hover table-striped">
                    <thead>
                        <tr>
                         <th>Id</th>
                        <th>Project Name</th>
                        <th>Url</th>
                        <th>Action</th>
						<th>App</th>
                         <th class="text-right">Options</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($sites as $site)
                            <tr>
                                <td>{{$site->id}}</td>
                     <td>{{$site->name}}</td>           
                    <td>
					<a href="http://{{$site->url}}" target ='_blank'>{{$site->url}}</a>
					</td>
                   
                    <td>{{$site->action_name}}</td>
					<td>{{$site->app_name}}
					
						@if($site->app_name == "WordPressPlusLaravel")
							@if($site->action_name == "New")
							<br />
							Laravel version: {{$site->laravel_version}}
							@endif
						@endif
					
					</td>
					
                                <td class="text-right">
                                   
                                   <a class="option_button" role="group" href="{{ route('sites.edit', $site->id) }}"> Options</a>
								   
								   @if(($pete_options->get_meta_value('snapshots') == "on") & ($site->app_name == "WordPress"))
								   
								    <a class="option_button create_snapshot" site_id="{{$site->id}}" href="#">Create Snapshot</a>
									
								   @endif
								    
									@if($site->app_name != "WordPressPlusLaravel")
								    <a class="option_button" href="/sites/export?id={{$site->id}}">Export</a>
									
									@if(!$site->suspend)
									<a class="option_button" href="/sites/suspend?id={{$site->id}}">Suspend</a>
									@else
									<a class="option_button" href="/sites/site_continue?id={{$site->id}}">Continue</a>
									@endif
									
									@endif
									
                                    <form action="{{ route('sites.destroy', $site->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="option_button" style="background-color: #f1592a; width: 100%">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $sites->render() !!}
            @else
                <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                           	<th>Project Name</th>
                        	<th>Url</th>
                        	<th>Action</th>
							<th>App</th>
                         	<th class="text-right">Options</th>
                        </tr>
                    </thead>

                    <tbody>
					</tbody>
					
				</table>
            @endif
			</div>
        </div>
    </div>
	
	
	
	<div class="modal fade">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	        <h4 class="modal-title">Modal title</h4>
	      </div>
	      <div class="modal-body">
			<form id="site_form" action="/snapshot_creation" style="display:none" method="POST">
				<input type="hidden" name="_method" value="POST">
				<input type="hidden" name="_token" value="{{ csrf_token() }}">         
			    <input type="hidden" id="snapshot_label_form" name="snapshot_label_form" value="">
				<input type="hidden" id="site_id_form" name="site_id_form" value="">
			    <input type="submit" />
			</form>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <button type="button" class="btn btn-primary">Save changes</button>
	      </div>
	    </div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	
	
	
	<script type="text/javascript">
	
	
	   
	
    	$(document).ready(function(){
			
  			@if(isset($exporturl))
				console.log("download url: {{$exporturl}}");
  		  		window.location.assign("/{{$exporturl}}");
  		
  		  @endif
				
			
			$(".create_snapshot").click(function() {
				site_id = $(this).attr("site_id");
				
			    BootstrapDialog.show({
			          title: 'Create Snapshot',
			          message: '<label>Label</label><br /><input id="snapshot_label" name="snapshot_label" value="">',
			          buttons: [{
			               label: '<a class ="btnpete">Create Snapshot</a>',
			              action: function(dialog) {
			                  // submit the form
							  snapshot_label = $("#snapshot_label").val();
							  $("#site_id_form").val(site_id);
							  $("#snapshot_label_form").val(snapshot_label);
			                  $('#site_form').submit()
			              }
			          }]
			      });
				
			});
			
        	//demo.initChartist();
			/*
        	$.notify({
            	icon: 'pe-7s-arc',
            	message: "Welcome to the future of OZONE. Welcome to <b>Massive Server</b>"

            },{
                type: 'info',
                timer: 4000
            });
			*/
			
			
		   @if(isset($success))
			
			@if($success == "true")
			
		    var delayInMilliseconds = 3000; //1 second

		    setTimeout(function() {
		      //your code to be executed after 1 second
		   	 $("#loadMe").modal("hide");
		    }, delayInMilliseconds);

		     $.ajax({
		           url: "/reload_server",
		           type: "get",
		           datatype: 'json',
				   data: {site_id : "{{$site_id}}}"},
		           success: function(data){
		            // alert("success");	
	
		           }
		
		     });

		    @endif
			 
		  @endif	
		   

    	});
		
		
	</script>
	

@endsection